# Used only for object storage-level tests with isolated MinIO settings.
#
# Usage: docker-compose -f docker-compose.base.yml -f docker-compose.test_objstr_minio.yml up -d
services:
  minio-test:
    image: minio/minio
    container_name: minio-test
    ports:
      - "9002:9000"   # Exposed S3 API for test
      - "9003:9001"   # Web console (test)
    environment:
      MINIO_ROOT_USER: testminio
      MINIO_ROOT_PASSWORD: testminio123
    command: server /data --console-address ":9001"
    volumes:
      - minio_test_data:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 10s
      retries: 5
    networks:
      - mlopsnet

networks:
  mlopsnet:
    external: true

volumes:
  minio_test_data:
